
	body  {
		background: <?php echo $this->style['BGColor']; ?>;
		font-family: Verdana, Helvetica, Arial, sans-serif;
		color: <?php echo $this->style['TextColor']; ?>;
		font-size: 80%;
		margin: 5px;
		padding: 0px;
		border: 0px;
	}

	.header { font-size: 175%; font-weight: bold; text-align: center; color: <?php echo $this->style['HRColor']; ?>; }
	.body { text-align: center; font-size: 100%; color: <?php echo $this->style['TextColor']; ?>; font-family: Verdana, Helvetica, Arial, sans-serif; }
	.footer { font-size: 100%; text-align: center; font-style: oblique }
	.copy { font-size: 10px; color: <?php echo $this->style['PoweredByColor']; ?>; text-align: center }
	.timeline { font-size: 10px; color: <?php echo $this->style['TimeColor']; ?>; text-align: left }
	.name { font-size: 125%; font-family: Times New Roman, Times Roman, Times, serif }
	hr { background-color: <?php echo $this->style['HRColor']; ?>; color: <?php echo $this->style['HRColor']; ?>; border: 0px; }
	h1, h3, h5 { color: <?php echo $this->style['HRColor']; ?>; }
	h2, h4, h6 { color: <?php echo $this->style['HRColor2']; ?>; }

/* Fucking IE needs a fucking hack because it doesn't understand transparent borders. */
	*html a:link, *html a:visited { border-color: <?php echo $this->style['BGColor']; ?>;  }

/* Links */
	a:link, a:visited { color: white; border: 1px solid transparent; padding: 1px }
	a:link:hover, a:visited:hover { border: 1px solid <?php echo $this->style['TextColor']; ?>; text-decoration: none; background-color: <?php echo $this->style['DarkTextColor']; ?>}
	a:link.namer { background-color: black; border: 0px; text-decoration: none }
	a:link:hover.namer { background-color: black; border: 0px; text-decoration: none }
	a:visited.namer { background-color: black; border: 0px; text-decoration: none }

/* The powered-by link is hidden */
	.copy a, .copy a:link, .copy a:visited, .copy a:active, .copy a:hover {
		color: <?php echo $this->style['PoweredByColor']; ?>;
		border: 0px;
		padding: 0px;
		background-color: <?php echo $this->style['BGColor']; ?>;
		text-decoration: none;
	}
	.copy a:hover {
		text-decoration: underline;
	}

/* Pre tags tend to get a little funky... */
	pre { font-family: Courier New, Courier, fixed; font-size: 125%; }

/* Message lines in the chat */
	.messageline { padding: 0px 0px 6px 10px; font-size: 100%; font-family: Verdana, Arial, Helvetica, sans-serif  }
	.thename { font-size: 150%; font-family: Times New Roman, Times Roman, Times, serif; font-weight: bold  }
	.thecaption { font-size: 90%; font-family: Verdana, Arial, Helvetica, sans-serif }
	.thelinks { font-size: 140%; font-family: Wingdings }
	.thetime { font-size: 80%; font-family: Verdana, Arial, Helvetica, sans-serif }
	.themessage { font-size: 100%; font-family: Verdana, Arial, Helvetica, sans-serif }
/* Links in the message line */
	a.url, a.email {
		border: 0px;
		margin: 0px;
		padding: 0px;
		margin-left: 2px;
		margin-right: 2px;
		text-decoration: none;
		background-repeat: no-repeat;
		background-position: top left;
		display: -moz-inline-block;
		display: inline-block;
	}
	a.url {
		font-size: 10px;
		height: 13px;
		width: 10px;
		background-image: url(wingdings-letter.png);
	}
	a.email {
		font-size: 10px;
		height: 13px;
		width: 17px;
		background-image: url(wingdings-envelope.png);
	}
	a:hover.url, a:hover.email {
		border: 0px;
		background-color: white !important;
	}

/* New user welcome */
	.messageline.welcome { color: <?php echo $this->style['DarkTextColor']; ?>; }
	.messageline.welcome .star { color: <?php echo $this->style['TextColor']; ?>; }

/* Posting form */
	.button, .textbox, .textarea, input[type=submit], input[type=button], input[type=text], select, textarea {
		background-color : <?php echo $this->style['BGColor']; ?>;
		border: 1px solid <?php echo $this->style['BorderColor']; ?>;
		font-size : 11px;
		color: <?php echo $this->style['TextColor']; ?>;
		font-family : verdana, arial, sans-serif;
	}
	.button {
		cursor: hand;
		cursor: pointer;
	}
	.textbox {
		width: 145px;
	}
	.textarea {
		width: 520px;
		height: 35px;
	}
	.namer {
		cursor: hand;
		cursor: pointer;
	}

/* Hover magic for browsers that don't understand non-anchor based hover/focus is provided via jQuery */
	.textbox:hover, .textarea:hover, .button:hover, .textbox:hover, .textarea:hover, .button:hover,
	input[type=submit]:hover, input[type=button]:hover, input[type=text]:hover, select:hover, textarea:hover {
		border-color: <?php echo $this->style['HRColor']; ?>;
	}
	.textbox:focus, .textarea:focus, .button:focus, .textbox.focus, .textarea.focus, .button.focus,
	input[type=submit]:focus, input[type=button]:focus, input[type=text]:focus, select:focus, textarea:focus,
	.textbox:active, .textarea:active, .button:active,
	input[type=submit]:active, input[type=button]:active, input[type=text]:active, select:active, textarea:active {
		border-color: <?php echo $this->style['HRColor2']; ?>;
		background-color: <?php echo $this->style['BGLightColor']; ?>;
	}
	input.disabled, input[disabled], button.disabled, button[disabled] {
		color: <?php echo $this->style['DarkTextColor']; ?> !important;
		border-color: <?php echo $this->style['DarkTextColor']; ?> !important;
		background-color: <?php echo $this->style['BGLightColor']; ?> !important;
	}

/* Ajax loader */
	#ajaxloader {
		height: 18px;
		width: 20px;
		position: absolute;
	}
	#ajaxloader.loading {
		background-image: url({$style[AjaxLoader]});
		background-attachment: scroll;
		background-position: center center;
		background-repeat: no-repeat;
	}

/* Multichat bits */
	#multichat-name-pick-list {
		border-collapse: separate;
		margin: 0px;
		margin-bottom: 3px;
		padding: 0px;
		border: 0px;
	}
	#multichat-name-pick-list td {
		font-size: 90%;
		padding: 1px;
		padding-left: 5px;
		padding-right: 5px;
		text-align: center;
		border: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
		border-top: 0px;
		border-left: 0px;
		border-right: 0px;
	}
	#multichat-name-pick-list td.picked {
		border: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
		border-bottom: 0px;
	}
	#multichat-name-pick-list td.picked span.yoink {
		display: inline;
		color: red;
		margin-left: 5px;
		cursor: hand;
		cursor: pointer;
	}
	#multichat-name-pick-list td.picked span.yoink:hover {
		text-decoration: underline;
	}
	#multichat-name-pick-list td span.yoink {
		display: none;
	}
	#multichat-name-pick-list td.adder {
		border-bottom: 0px;
		border-left: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
		border-top: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
		text-align: center;
		font-weight: bold;
		cursor: hand;
		cursor: pointer;
	}
	#multichat-name-pick-list td .name {
		font-size: 110%;
		font-weight: normal;
		cursor: hand;
		cursor: pointer;
	}
	#multichat-name-pick-list td.picked .name {
		font-size: 115%;
		font-weight: bold;
		cursor: hand;
		cursor: pointer;
	}

/* Color picker */
	.colorpicker-cell {
		height: 15px;
		width: 15px;
		float: left;
		border: 1px dotted <?php echo $this->style['BorderColor']; ?>;
		margin: 2px;
	}

/* Guard page: main table cell magic */
	#bantable {
		border: 2px solid <?php echo $this->style['BanColor']; ?>;
		width: 172px;
		margin: 0px;
		padding: 0px;
		border-collapse: separate;
	}
	#bantable tr.bantoprow, #bantable tr.banbotrow {
		cursor: pointer;
		cursor: hand;
	}
	#bantable tr.bantoprow td, #bantable tr.banbotrow td {
		border: 2px solid <?php echo $this->style['BGColor']; ?>;
	}
	#bantable td.banbtncell {
		border-right: 0px !important;
	}
	#bantable td.bannamecell {
		border-bottom: 0px !important;
		border-left: 0px !important;
	}
	#bantable td.banipcell {
		border-top: 0px !important;
		border-left: 0px !important;
	}
	#bantable td.banipcell small {
		color: <?php echo $this->style['TextColor']; ?>;
	}
/* Guard page: main table cell magic part 2 */
	#bantable td.banbtncell.active,
	#bantable td.bannamecell.active,
	#bantable td.banipcell.active {
		border-color: <?php echo $this->style['BanColor']; ?>;
		background-color: <?php echo $this->style['BGLightColor']; ?>;
	}
/* Guard page: Make it all fit... */
	#banopttable {
		width: 174px;
	}
	#banopttable td {
		font-size: 10px;
	}
	#banopttable .textbox {
		width: 122px;
	}
	#banrefreshbtn, #banrefreshbtn_top, #bankickbtn {
		width: 172px;
	}
/* Guard page: List of active and lifted bans */
	.bannedstart {
		color: <?php echo $this->style['BanColor']; ?>;
	}
	.bannedend {
		color: <?php echo $this->style['TimeColor']; ?>;
	}
	.bannedreason {
		color: <?php echo $this->style['BanHiliteColor']; ?>;
	}
	.bannedlifted {
		color: <?php echo $this->style['BanLiftColor']; ?>;
		font-style: italic;
	}
/* Guard page: List of bans */
	.banlist {
		width: 174px !important;
		font-size: 77.5%;
		border-collapse: collapse;
	}
	.banlist td {
		vertical-align: top;
	}
	.banlist .l {
		text-align: right;
	}
	.banlist .t {
		white-space: nowrap;
	}
	.banlist th {
		border-top: 1px solid <?php echo $this->style['HRColor']; ?>;
	}

/* Control Panel Pages */
	.cpanel-wrapper {
		width: 660px;
		text-align: left;
		margin: auto;
	}

/* Control Panel Page: Settings */
	#cpanel-settings {
		font-size: 90%;
		border-collapse: collapse;
	}
	#cpanel-settings tr {
		border-top: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
	}
	#cpanel-settings th {
		color: <?php echo $this->style['HRColor']; ?>;
		font-size: 120%;
		border: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
	}
	#cpanel-settings .l {
		font-weight: bold;
		font-size: 105%;
	}
	#cpanel-settings .l span {
		font-weight: normal;
		font-size: 80%;
	}
/* Control Panel Page: Login Manager */
	#cpanel-login-list {
		font-size: 90%;
		border-collapse: collapse;
	}
	#cpanel-login-list tr {
		border-top: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
	}
	#cpanel-login-list th {
		color: <?php echo $this->style['HRColor']; ?>;
		font-size: 120%;
		border: 1px solid <?php echo $this->style['MultiChatBorder']; ?>;
	}


/* Log viewer: IP address */
	div.log-ip {
		font-size: 80%;
		font-weight: bold;
		margin-left: 2em;
		color: <?php echo $this->style['HRColor']; ?>;
	}
