<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN"
   "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<head>
	<title><?php echo $this->config['ChatName']; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<frameset rows="<?php echo ($this->show_chat_top ? $this->chat_top_pixels . ',*,130' : '*,130'); ?>" border="0">
<?php if($this->show_chat_top): ?>
	<frame src="<?php echo $this->chat_top_file; ?>" name="eltop" scrolling="no">
<?php endif; ?>
<?php if($this->is_guard): ?>
	<frameset cols="*,210" border="2">
<?php endif; ?>
	<frame src="<?php echo $this->messages_url; ?>" name="messages" scrolling="auto">
<?php if($this->is_guard): ?>
	<frame src="<?php echo $this->guard_script_url ?>" name="ips" id="ips" scrolling="auto">
	</frameset>
<?php endif; ?>
	<frame src="chat3.cgi" name="input" scrolling="no">
</frameset>
</html>
