<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN"
   "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<head>
	<title><?php echo $this->chat_name; ?></title>
</head>
<frameset rows="<?php echo ($this->show_chat_top ? $this->chat_top_pixels . ',*,130' : '*,130'); ?>" border="0">
<?php if($this->show_chat_top): ?>
	<frame src="<?php echo $this->chat_top_file; ?>" name="eltop" scrolling="no">
<?php endif; ?>
	<frame src="messages.html" name="messages" scrolling="auto">
	<frame src="chat3.cgi" name="input" scrolling="no">
</frameset>
</html>
