<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->config['ChatName']; ?> - Messages</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="<?php echo $this->config['CSSName']; ?>">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->config['NonCGIURL']; ?>/natter.js"></script>
	<script type="text/javascript">
		var newest_id = <?php echo $this->newest_id; ?>;
		var max_messages = <?php echo $this->config['MessageLimit']; ?>;
		var script_name = '<?php echo $this->config['IndexName'] ?>';
		var timeout = null;
	// Onload GO.
		$().ready(function(){
			$().ajaxStart(ajax_loader_start);
			$().ajaxComplete(ajax_loader_end);
			timeout = setTimeout(messages_refresh, 8000);
		});

	// Try to use the ajax loading image in the form frame, if we can.
		function ajax_loader_start() {
			if(window.parent && window.parent.input && window.parent.input.ajax_loader_start)
				window.parent.input.ajax_loader_start();
		} // end ajax_loader_start
		function ajax_loader_end() {
			if(window.parent && window.parent.input && window.parent.input.ajax_loader_end)
				window.parent.input.ajax_loader_end();
		} // end ajax_loader_end

	</script>
</head>
<body>
<div id="message_container">
<?php
	foreach($this->lines as $k => $line) {
		if(!is_numeric($k))
			continue;
		echo $line . "\n";
	} // end foreach
	echo "</div>\n";
	include 'poweredby.phtml';
?>
</body>
</html>
