<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->config['ChatName']; ?></title>
	<link rel="stylesheet" href="<?php echo $this->config['CSSName']; ?>">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->config['NonCGIURL']; ?>/natter.js"></script>
	<script type="text/javascript">
		var presence_data = {};
		var presence_timer = 15;
		var presence_settimeout = null;
		$().ready(function(){
			$().ajaxStart(ajax_loader_start);
			$().ajaxComplete(ajax_loader_end);
			refresh_presence();
		});

	// Refresh presence info.
		function refresh_presence() {
			$.post(
				'<?php echo $this->config['IndexName']; ?>',
				{
					action: 'presence',
					do: 'get'
				},
				function(data, status) {
					if(status == 'success') {
						presence_data = data.presence_data;
						$('#presence').html(data.presence_html);
					} // end if
					setTimeout(refresh_presence, presence_timer * 1000);
				},
				'json'
			);
		} // end refresh_presence

	// Try to use the ajax loading image in the form frame, if we can.
		function ajax_loader_start() {
			if(window.parent && window.parent.input && window.parent.input.ajax_loader_start)
				window.parent.input.ajax_loader_start();
		} // end ajax_loader_start
		function ajax_loader_end() {
			if(window.parent && window.parent.input && window.parent.input.ajax_loader_end)
				window.parent.input.ajax_loader_end();
		} // end ajax_loader_end

	</script>
</head>
<body>
	<div id="presence"></div>
</body>
</html>
